baseurl = "http://www.journal.roperzh.com/es/"
languageCode = "es"
title = "Merging the merge"
contentdir = "content/es"
publishdir = "public/es"
theme="journal-theme"
copyright="&copy; Copyright 2016 Roberto Dip"

[params]
    locale = "es"
    twitter = "roperzh"
    github = "roperzh"

