baseurl = "http://www.journal.roperzh.com/en/"
languageCode = "en-us"
title = "Merging the merge"
contentdir = "content/en"
publishdir = "public/en"
theme = "journal-theme"
copyright = "&copy; Copyright 2016 Roberto Dip"
googleAnalytics = "UA-73160048-1"

[params]
    locale = "en-us"
    twitter = "roperzh"
    github = "roperzh"
    disqusShortname = "journal-roperzh-en"